### ISSUE TITLE
Exception when running tests: java.lang.NoSuchMethodError: org/junit/runner/Description.createTestDescription(Ljava/lang/String;Ljava/lang/String;Ljava/io/Serializable;)Lorg/junit/runner/Description;

### ISSUE THREAD

**Issue by wjbolles** [Pragmatists/JUnitParams#50]
Hello,

When using JUnitParams 1.0.4 with JUnit 4.10 I run into this exception when I run my unit tests:

    java.lang.NoSuchMethodError: org/junit/runner/Description.createTestDescription(Ljava/lang/String;Ljava/lang/String;Ljava/io/Serializable;)Lorg/junit/runner/Description;
    at junitparams.internal.TestMethod.describe(TestMethod.java:106)
    at junitparams.internal.ParameterisedTestClassRunner.describeParameterisedMethod(ParameterisedTestClassRunner.java:162)
    at junitparams.JUnitParamsRunner.describeMethod(JUnitParamsRunner.java:460)
    at junitparams.internal.ParametrizedTestMethodsFilter.filteredMethods(ParametrizedTestMethodsFilter.java:30)
    at junitparams.JUnitParamsRunner.getListOfMethods(JUnitParamsRunner.java:456)
    at junitparams.JUnitParamsRunner.getDescription(JUnitParamsRunner.java:445)
    at org.junit.runner.Runner.testCount(Runner.java:38)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.countTestCases(JUnit4TestClassReference.java:30)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.countTests(RemoteTestRunner.java:487)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:455)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

I tried using JUnitParams 1.0.0 and it worked successfully.

Regards,

Walter

**Comment by jtbeckha** [comment]
Seems to work with JUnitParams 1.0.4 and JUnit 4.12 as well

**Comment by Zoltu** [comment]
For me the error was thrown because my test method was private.  A better error message would have been nice.

**Comment by GuiSim** [comment]
Using the latest version of JUnitParams and JUnit solved the issue for me.

**Comment by jrmichael** [comment]
Since it works with newer JUnit I am closing this issue.

**Comment by tjtaill** [comment]
I am still seeing this issue with Junit 4.12 running in eclipes mars with JUnitParams 1,0,4

**Comment by Beanson** [comment]
my package list : juit-4.12;hamcrest-core-1.3;hamcrest-library-1.3 run well

**Comment by Brijendra9322** [comment]
i am still facing issue with 4.12.running on eclipse juno.

**Comment by acotis** [comment]
Hello all,
I had a similar issue as MicahZoltu.  My problem was that the test method was static.  Changing it to non-static solved the issue.  Hope this helps.

**Comment by aaa1999** [comment]
> Since it works with newer JUnit I am closing this issue.

Yeah,I tried it,And it worked.
